### PR TITLE
ritik

### PR DESCRIPTION
**Pull request by ritikagarwal231**

### CODE REVIEW

**Comment by parikshit223933** [comment]
Is the existing solution failing on some test cases?

**Comment by ritikagarwal231** [comment]
> Is the existing solution failing on some test cases?

Yes, For test case 4 and 6 , time limit was exceeding in your solution.
I tried doing it with another approach and it worked.

**Comment by parikshit223933** [comment]
Thank you for contributing to this repository.

**Comment by ritikagarwal231** [comment]
Tbh i should thank you for all the solutions. And for making all the work and fast. 
Thank you sir for everything 😄😄

**Pull request merged**
