### PR TITLE
Updated Warm_Reception

### PR DESCRIPTION
**Pull request by nirbhayjain20**
This could be a better and short approach if you like.

### CODE REVIEW

**Comment by parikshit223933** [comment]
Hello @nirbhayjain20 Thank you for contributing to this repository.
Can you please create another file named "Warm_Reception_another_approach.cpp" and make the changes there and create a pull request instead of making changes in original file?
This way people will be able to see multiple approaches to the same problem.

**Comment by parikshit223933** [comment]
Closing due to inactivity.

**Comment by nirbhayjain20** [comment]
> Closing due to inactivity.

So sorry i was inactive for these many days due to my exams. Can i make the pool now if you would consider that?

**Comment by parikshit223933** [comment]
Sure. You can generate another PR.
PS: Please read the <a href="https://github.com/parikshit223933/Coding-Ninjas-Competitive-Programming#user-content-contribution">contribution guidelines</a> first.

**Pull request closed without merging**
